DROP TABLE IF EXISTS Directors_Movies;
DROP TABLE IF EXISTS Producers_Movies;
DROP TABLE IF EXISTS Genres_Movies;
DROP TABLE IF EXISTS Categories_Movies;
DROP TABLE IF EXISTS Cast;
DROP TABLE IF EXISTS Movies_Awards;
DROP TABLE IF EXISTS Ratings;

DROP TABLE IF EXISTS Movies;
DROP TABLE IF EXISTS Users;
DROP TABLE IF EXISTS Directors;
DROP TABLE IF EXISTS Producers;
DROP TABLE IF EXISTS Genres;
DROP TABLE IF EXISTS Categories;
DROP TABLE IF EXISTS Awards;
DROP TABLE IF EXISTS Actors;
